/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Audio, Image, Pdf, Video } from "@boundaryml/baml"
import type * as types from "./types.js";
import type {
  Article,
  Check,
  Checked,
  DailyDigest,
  MainStory,
  OtherTopic,
} from "./types.js";

/******************************************************************************
 *
 *  These types are used for streaming, for when an instance of a type
 *  is still being built up and any of its fields is not yet fully available.
 *
 ******************************************************************************/

export interface StreamState<T> {
  value: T;
  state: "Pending" | "Incomplete" | "Complete";
}

export namespace partial_types {
  export interface Article {
    title?: string | null;
    snippet?: string | null;
    content?: string | null;
  }
  export interface DailyDigest {
    digest_title?: string | null;
    overview?: string | null;
    main_stories: MainStory[];
    other_topics: OtherTopic[];
  }
  export interface MainStory {
    headline?: string | null;
    summary?: string | null;
    category?: string | null;
  }
  export interface OtherTopic {
    topic?: string | null;
    brief_update?: string | null;
  }
}
